export const profileLabels = {
  en: {
    myProfile: 'My Profile',
    edit: 'Edit',
    shopDetails: 'Shop Details',
    ownerDetails: 'Owner Details',
    contactInfo: 'Contact Info',
    businessInfo: 'Business Info',
    earnings: 'Earnings',
    lowInventory: 'Low Inventory Items',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    growth: 'Growth',
    okay: 'Okay',
    ignore: 'Ignore',
    outOfStock: 'Out of Stock',
    lowStock: 'Low Stock',
    pieces: 'pcs',
    language: 'Language',
    english: 'English',
    hindi: 'हिंदी'
  },
  hi: {
    myProfile: 'मेरी प्रोफ़ाइल',
    edit: 'संपादित करें',
    shopDetails: 'दुकान का विवरण',
    ownerDetails: 'मालिक का विवरण',
    contactInfo: 'संपर्क जानकारी',
    businessInfo: 'व्यवसाय की जानकारी',
    earnings: 'कमाई',
    lowInventory: 'कम इन्वेंटरी आइटम',
    thisMonth: 'इस महीने',
    lastMonth: 'पिछला महीना',
    growth: 'वृद्धि',
    okay: 'ठीक है',
    ignore: 'अनदेखा करें',
    outOfStock: 'स्टॉक खत्म',
    lowStock: 'कम स्टॉक',
    pieces: 'पीस',
    language: 'भाषा',
    english: 'English',
    hindi: 'हिंदी'
  }
};